export const leoRewrites = {
  "leo_0": [
    "Cuando el sol se esconde tras los pinos gigantes, la montaña empieza a enfriarse. Leo se ajusta bien sus botas de montaña y busca el [sendero](magic-word:sendero) de regreso a casa. ¡Sabe que debe tener paciencia y pisar con firmeza en la tierra!",
    "De pronto... una densa [bruma](magic-word:bruma) blanca baja del cielo y cubre los árboles altos. Leo ya no puede ver las piedras del camino y se detiene preocupado. Pero recuerda respirar con calma e iluminar sus pasos con su Linterna de Oro.",
    "El sendero se adentra en una zona de maleza [espesa](magic-word:espesa) que protege la entrada de su casa. Leo avanza alumbrando el suelo y se alegra al ver su cabaña a lo lejos. Al fondo, divisa una cueva misteriosa... ¡que explorará en su siguiente aventura!"
  ],
  "leo_1": [
    "Leo caminaba con gran paciencia por la base de la montaña. El suelo estaba cubierto de un [musgo](magic-word:musgo) verde muy suave. Todo estaba callado y tranquilo... esperando a ser despertado por un pequeño explorador valiente.",
    "De pronto, ¡descubrió un [destello](magic-word:destello) de luz dorada brillando bajo una hoja! Leo se acercó sin apuro, sabiendo que el coraje empieza observando con calma. Iluminó la sombra usando su Linterna de Oro.",
    "Al limpiarla, la piedra emitió un suave [silbido](magic-word:silbido) musical, cantando una nota alta. Leo guardó esta Piedra de Eco. Mientras se levantaba... un crujido de ramas secas a lo lejos lo invitó hacia un viejo puente misterioso."
  ],
  "leo_2": [
    "Siguiendo el ruido, Leo llegó a un inmenso puente de fuertes [raíces](magic-word:raíces) entrelazadas. ¡Para cruzar este desafío, debía ser valiente! Puso un pie lentamente delante del otro, manteniendo su mente enfocada en el frente.",
    "A la mitad del camino, escuchó un fuerte [crujido](magic-word:crujido) bajo sus botas. Miró el profundo [abismo](magic-word:abismo), pero en vez de asustarse... respiró profundo. Su luz dorada le mostraba que las raíces eran firmes y seguras.",
    "¡Al cruzar con éxito, encontró la segunda Piedra que cantó dulcemente! El viento sopló fuerte entre los árboles, trayendo consigo el inconfundible olor a pino húmedo de una cueva oscura... que lo esperaba más arriba."
  ],
  "leo_3": [
    "El olor a pino guio sus pasos hasta una cueva. Adentro había mucha [penumbra](magic-word:penumbra). Leo sintió un poquito de susto inicial... pero encendió su linterna mágica sabiendo que la luz siempre ilumina hasta el rincón más oscuro.",
    "Caminando paso a paso, vio que las paredes eran de hermoso [ámbar](magic-word:ámbar) brillante. ¡Este lugar era un antiguo [refugio](magic-word:refugio) seguro y tranquilo! La inmensa cueva entera brillaba como si estuviera hecha de oro.",
    "La luz liberó la tercera Piedra redonda, que cantó alegre. Guardó su premio en la mochila. Justo entonces... unas pequeñas huellas de patitas marcadas en el polvo lo invitaron a salir hacia la salida."
  ],
  "leo_4": [
    "Siguiendo los rastros de polvo, Leo encontró a un zorrito solitario tiritando fuera de su [madriguera](magic-word:madriguera). ¡El animalito sentía mucho frío y miedo! Leo demostró bondad y se acercó despacio para no asustarlo más.",
    "El zorrito tenía un [temblor](magic-word:temblor) incontrolable. Leo, con gran resiliencia y cariño, le ofreció el cálido [cobijo](magic-word:cobijo) de su chaqueta de lana. Sentarse en silencio a acompañar a un amigo... ¡es un acto muy valiente!",
    "El zorro, muy agradecido, escarbó la tierra y le regaló la cuarta Piedra de Eco. A lo lejos, el rugido ruidoso de un caudaloso río comenzó a llamar la atención de Leo... invitándolo a una nueva aventura."
  ],
  "leo_5": [
    "Siguiendo la invitación del río, Leo descubrió un inmenso [torrente](magic-word:torrente) que caía con mucha fuerza desde las rocas más altas. Su constante [murmullo](magic-word:murmullo) asustaba a los pajaritos del bosque. Leo, muy valiente, caminó por el borde del agua buscando cuidadosamente qué provocaba un ruido tan grande en aquel paraíso acuático.",
    "Con persistencia, Leo descubrió que unas grandes ramas caídas bloqueaban el flujo del agua [cristalina](magic-word:cristalina). ¡Sin dudarlo, empujó la pesada madera con toda su fuerza! Demostrando que los más pequeños pueden mover grandes obstáculos. Poco a poco, el agua comenzó a fluir con tranquilidad nuevamente, recuperando su melodía.",
    "El agua se calmó por completo y dejó al descubierto la quinta Piedra de Eco brillante, que cantó una alegre nota aguda. Leo sonrió agradecido y la guardó con cariño. Al mirar hacia arriba... ¡notó una empinada escalera tallada directamente en la roca de la montaña!"
  ],
  "leo_6": [
    "Leo comenzó a subir la nueva montaña. Era un camino muy alto y de forma [escarpada](magic-word:escarpada). Nuestro explorador subió cada [peldaño](magic-word:peldaño) de piedra con paciencia y perseverancia. Sabía que rendirse nunca es una opción cuando persigues un sueño. Puso sus manos sobre la roca fría y continuó avanzando.",
    "Sus pequeñas piernas estaban cansadas, pero su corazón latía lleno de esperanza. Recordó que la imponente [cima](magic-word:cima) de la montaña siempre oculta un premio reservado para los niños valientes que nunca dejan de intentar. Tomó un largo respiro... y decidió dar los últimos tres pasos más difíciles del camino.",
    "¡En lo más alto de la escalera, halló la sexta Piedra mágica! Sonó dulcemente con un tono grave. Leo la acarició para agradecerle su música y recuperar energías. Mientras descansaba sentado en la roca plana... un extraño escarabajo dorado pasó volando frente a él, apuntando su camino hacia un bosque nublado."
  ],
  "leo_7": [
    "Siguiendo el vuelo del pequeño escarabajo, Leo entró en un lugar donde la niebla era [espesa](magic-word:espesa). Todo se veía borroso. Las montañas gigantes parecían monstruos gigantescos con brazos largos. Sin embargo, Leo sabía que los miedos a menudo son solamente ilusiones creadas por nuestra mente cuando no logramos ver claro.",
    "Caminando con cuidado, Leo notó una [silueta](magic-word:silueta) grande moviéndose cerca de un árbol antiguo. En vez de salir huyendo, confió en su [brújula](magic-word:brújula) interior. Iluminó la sombra con su linterna, descubriendo que aquella figura no era un monstruo temible... ¡sino un amistoso oso perezoso disfrutando de una siesta!",
    "Justo debajo de las grandes patas peludas del oso dormido, Leo encontró la séptima Piedra de Eco. Al tocarla con cuidado para no despertar al animal, la piedra soltó una melodía tranquilizadora. Una vez guardada... un viento muy helado sopló sobre su cara, advirtiéndole que la nieve estaba cerca."
  ],
  "leo_8": [
    "El frío intenso comenzó a sentirse con fuerza. Una dura capa de [escarcha](magic-word:escarcha) blanca cubría el rocoso suelo del sendero. Al intentar avanzar, las botas de Leo resbalaron sobre el hielo, pero supo sostenerse justo a tiempo agarrándose de una rama caída... ¡evitando así un fuerte golpe en sus rodillas!",
    "A pesar de tener cuidado, Leo sufrió un pequeño [resbalón](magic-word:resbalón) que lo dejó sentado en la nieve. En lugar de enojarse, ¡simplemente se rio de la situación y se levantó rápido! Aprendió que caminar con absoluta [firmeza](magic-word:firmeza) requiere práctica constante, y que caerse de vez en cuando es normal.",
    "Al limpiar la nieve de su ropa mojada, descubrió una hermosa Piedra de Eco congelada. Cuando la sostuvo entre sus manos calientitas, la piedra se derritió un poco y cantó una canción cristalina. En ese momento de tranquilidad... escuchó el agudo graznido de un águila majestuosa volando sobre los picos nevados."
  ],
  "leo_9": [
    "Guiado por el fuerte graznido del ave, Leo subió por la ladera. Una fuerte [ventisca](magic-word:ventisca) de nieve soplaba intentando detener su avance. De pronto... ¡vio a un pequeño pajarito llorando escondido detrás de una roca! Tenía muchísimo miedo de intentar volar en medio de aquellos fuertes vientos helados.",
    "Leo sintió mucha pena por la avecilla. Usando su pesada chaqueta y unas rocas cercanas, construyó rápidamente un [refugio](magic-word:refugio) temporal para protegerla del clima. Él comprendía que ser valiente no significa no sentir miedo nunca, sino usar tu propia fuerza interior para poder cuidar a los más vulnerables.",
    "El pajarito, sintiéndose protegido y muy agradecido, le regaló a nuestro héroe una brillante [pluma](magic-word:pluma) azul y la novena Piedra mágica que emitía un sonido relajante. Más allá de la roca protectora, la blanca niebla comenzó a despejarse mágicamente... ¡permitiendo que la gran cumbre final fuera visible en su esplendor!"
  ],
  "leo_10": [
    "Mientras Leo avanzaba maravillado hacia la imponente montaña, tuvo que atravesar un larguísimo cañón de paredes grises. De pronto, un misterioso [eco](magic-word:eco) comenzó a rebotar por todo el lugar, repitiendo palabras desmotivadoras que le decían que retrocediera inmediatamente, afirmando que era demasiado pequeño para una montaña tan grande. El constante sonido rebotaba, intentando llenar su corazón de dudas.",
    "Leo se detuvo un segundo, sintiendo una pequeña punzada de temor en su pecho. Sin embargo, rápidamente se dio cuenta de que aquellas palabras eran simplemente un [engaño](magic-word:engaño) provocado por el viento al chocar contra las piedras huecas. Recordando las pruebas que ya había superado, caminó hacia adelante con absoluta [certeza](magic-word:certeza) y gran valentía, demostrando que confiar en nuestras propias habilidades es la herramienta más poderosa para callar a cualquier voz negativa.",
    "Leo descubrió el exacto agujero en la roca por donde el molesto viento entraba para crear aquellos engañosos sonidos. Al taparlo cuidadosamente usando una piedra redonda, logró extraer de su interior la décima Piedra de Eco, ¡la cual entonó una melodía verdaderamente fuerte y muy victoriosa! Apenas guardó su recompensa, observó cómo una gigantesca nube blanca comenzó a disolverse... revelando la entrada hacia una cueva de puro hielo."
  ],
  "leo_11": [
    "Leo ingresó con cuidado a la profunda [bóveda](magic-word:bóveda) subterránea de aquella espectacular cueva helada. Al tocar suavemente una de las inmensas rocas congeladas... ¡esta resonó con un sonido tan limpio que parecía una campana de oro! El inmenso lugar estaba repleto de estalactitas gigantes que colgaban afiladas desde el techo, creando un pasillo bellísimo pero peligroso, ya que cualquier ruido fuerte podría hacer que cayeran al frágil suelo.",
    "Nuestro increíble héroe pronto comprendió que cada simple paso producía un sonoro [repique](magic-word:repique) al golpear contra el duro [cristal](magic-word:cristal) del resbaladizo piso congelado. Para evitar cualquier accidente en aquel laberinto delicado, Leo debía moverse rítmicamente, casi como si estuviera realizando una antigua danza de puntillas, asegurándose de que sus pies acompañaran suavemente la musicalidad natural. Aprender a controlar nuestro cuerpo en situaciones difíciles es una muestra de inteligencia, paciencia y autocontrol.",
    "La hermosa danza de nuestro querido Leo generó una vibración tan armónica que terminó rompiendo pacíficamente una fina capa de hielo azul en la gran pared central, ¡dejando totalmente al descubierto la undécima Piedra mágica! Con una inmensa sonrisa de orgullo por su increíble delicadeza, Leo guardó la piedra en su abrigo calientito. Solamente le faltaba ahora escalar una última ladera cubierta de nieve para alcanzar la luminosa cumbre."
  ],
  "leo_12": [
    "Apenas Leo logró salir de la fría cueva de cristal, el clima de la montaña cambió de forma brutal y repentina. Una inmensa [ráfaga](magic-word:ráfaga) de viento congelado, mucho más fuerte que cualquiera de las anteriores, intentó empujarlo sin piedad hacia abajo. La nieve caía con tal intensidad que le bloqueaba su valiosa vista, haciendo que cada paso fuera una verdadera lucha titánica contra la furia de la tormenta natural.",
    "Pero nuestro valiente Leo, demostrando una fortaleza impresionante, clavó firmemente sus resistentes botas en la gruesa nieve y se inclinó hacia adelante. Su inquebrantable [voluntad](magic-word:voluntad) de hierro le recordaba que no debía rendirse jamás cuando su meta estaba ya tan cerquita. Él sabía que absolutamente todas las tormentas terminan pasando siempre y cuando mantengas la fe. Cerró los ojos un instante, confió en su potente Linterna de Oro... ¡y continuó firme!",
    "Lentamente, el furioso e indomable viento comenzó a perder su terrible fuerza y la espesa tormenta se disipó finalmente en el cielo azul. Al calmarse el entorno nevado, Leo encontró semi enterrada bajo la nieve fresca la duodécima mágica Piedra de Eco, la cual resplandecía intensamente para celebrar su inmenso coraje. Al levantar nuevamente su agotada mirada heroica... ¡pudo observar con profunda alegría que la [cumbre](magic-word:cumbre) mayor de la montaña estaba a pocos metros!"
  ],
  "leo_13": [
    "El último tramo del heroico camino era sin duda alguna el más escarpado y difícil de todo su largo viaje. Las piernas de Leo sentían una pesada [fatiga](magic-word:fatiga) acumulada después de haber superado tantos desafíos desde la base. Quedaba un único reto gigantesco y agotador frente a sus valientes ojitos: escalar gloriosamente una altísima pared vertical de pura roca lisa que bloqueaba su tan anhelado paso hacia el majestuoso Faro de la Tierra.",
    "Deteniéndose serenamente un corto segundo frente a la inmensa muralla infranqueable, Leo tomó un muy profundo [aliento](magic-word:aliento). Nuestro explorador sabía que absolutamente todos los grandes logros de la historia requieren realizar un definitivo esfuerzo final. Concentrando resueltamente la inmensa fuerza imparable de su valeroso corazón, aferró fuerte sus manos a la fría pared rugosa y comenzó su ascenso vertical superando el dolor.",
    "¡Con un último e increíble impulso cargado de heroica resiliencia, Leo cruzó triunfalmente el gran [umbral](magic-word:umbral) rocoso! Encontró la penúltima brillante Piedra de Eco posada delicadamente sobre un pedestal de blanco mármol. La mágica piedra entonó una alegre melodía divina que hizo desaparecer inmediatamente su enorme cansancio corporal. Cuando nuestro pequeño gigante logró finalmente ponerse de pie sobre la piedra cimera... se encontró maravillado frente al épico e iluminado Gran Faro."
  ],
  "leo_14": [
    "Leo se paró silenciosamente, muy emocionado frente al imponente [faro](magic-word:faro) de piedra antigua que dominaba hermosamente toda la resplandeciente cima del inmenso mundo de nuestro amado Bioma de la Tierra. El frío viento invernal soplaba ahora con una delicada suavidad, como si la gigantesca montaña entera estuviera conteniendo la respiración, esperando con ansias el esperado milagro de luz. Con sus diminutas manos, nuestro valiente niño sacó orgullosamente todas y cada una de sus Piedras.",
    "Al colocar amorosamente la grandiosa y definitiva última piedra luminosa en su hueco central... ¡un resplandor dorado brillantísimo iluminó celestialmente el nublado cielo completo! Las hermosas piedras cantoras se encendieron deslumbrantemente unidas, esparciendo una melodía de infinita [armonía](magic-word:armonía) divina que viajó por toda la vasta montaña, despertando a los sabios osos y al zorro valiente. ¡La Tierra entera había vuelto a cantar y a brillar gracias al coraje de un noble niño!",
    "Mientras nuestro increíble héroe celebraba alegremente su triunfo bañado en la cálida y protectora luz del oro antiguo, una fresca brisa salada totalmente desconocida llegó sorpresivamente hasta la elevada cima. Dicha inusual brisa húmeda traía consigo el muy profundo [misterio](magic-word:misterio) de un enorme mar distante, acompañando un hermoso destello turquesa marino... sintiendo así, como si el muy lejano Bioma del Agua ahora pidiera ser heroicamente salvado por un nuevo corazón valiente."
  ]
};
