export const niaRewrites = {
  "nia_0": [
    "En el bioma del agua, el arrecife de coral brilla como un jardín lleno de luces. Nia nada libremente, moviendo sus manos de forma [serena](magic-word:serena) mientras saluda a los peces que despiertan en este pacífico mundo azul.",
    "De repente, ¡una veloz [corriente](magic-word:corriente) de agua fría cruza el arrecife! La arena del fondo se levanta y las burbujas de sonido se enredan, impidiendo que los pequeños caballitos de mar encuentren el camino de regreso a sus hogares.",
    "Nia saca su hermosa Caracola de [nácar](magic-word:nácar) brillante. Al soplarla, produce una nota musical limpia que calma las olas y devuelve el orden al arrecife. En su siguiente viaje... Nia investigará un caparazón antiguo que brilla con letras extrañas."
  ],
  "nia_1": [
    "Nia camina suavemente por la tranquila [costa](magic-word:costa) dorada. La pequeña niña cierra sus ojos para escuchar el dulce canto de las gaviotas blancas, que vuelan muy libres buscando alimento bajo el inmenso cielo azul.",
    "De repente, ¡la inmensa [marea](magic-word:marea) retrocede misteriosamente mucho más de lo normal! En la arena mojada descubre una zona llena de ruidos blancos y caóticos que interrumpen severamente la relajante melodía de la mañana.",
    "Para calmar el ruido ensordecedor, la valiente niña saca su antigua y mágica [caracola](magic-word:caracola) de nácar. Al acercarla lentamente a su oído, logra sintonizar el hermoso latido curativo del inmenso océano salado que siempre la protege."
  ],
  "nia_2": [
    "Con enorme cuidado y suavidad constante, Nia avanza lentamente dejando pequeñas huellas descalzas sobre la suave [arena](magic-word:arena) mojada. La brillante luz de la mañana refleja múltiples destellos mágicos iluminando todo su largo cabello.",
    "La sabia niña pacífica se sumerge en el agua maravillosamente [cristalina](magic-word:cristalina) y refrescante de la costa. Bajo las tenues olas, descubre con tristeza que un gran cardumen de peces naranjas nada descontroladamente... ¡porque olvidaron su ritmo natural!",
    "Nia nada lentamente hacia un gigantesco y colorido [arrecife](magic-word:arrecife) de coral vibrante. Allí usa su mágica caracola brillante para emitir una sola nota musical redonda, que tranquiliza rápidamente a todos los peces asustados que nadaban sin rumbo."
  ],
  "nia_3": [
    "Nia decide valientemente [bucear](magic-word:bucear) más profundo, alejándose poco a poco de la cálida luz dorada del sol. Sus lentos movimientos corporales son tan ligeros y precisos como los de un ágil delfín explorador del fondo.",
    "En la oscuridad encuentra a una hermosa [medusa](magic-word:medusa) azul... ¡que gira violentamente sin poder detenerse jamás! Un ruido súper estresante y molesto confunde por completo a la delicada criatura marina causándole un enorme mareo y una pérdida de dirección.",
    "La niña sintoniza su caracola blanca con el sonido exacto de la inmensa [corriente](magic-word:corriente) submarina protectora. El agua sanadora comienza a fluir ordenadamente y la frágil criatura luminosa finalmente logra descansar en perfecta paz, meciéndose con enorme dulzura."
  ],
  "nia_4": [
    "Mientras desciende con mucha paz, Nia observa miles de pequeñitas [burbujas](magic-word:burbujas) plateadas subiendo rápidamente. Sin embargo, ella sabe que debe ser muy paciente y no intentar perseguirlas, porque su verdadera misión requiere total concentración y más bajada ininterrumpida.",
    "Un gran cangrejo de caparazón sumamente [brillante](magic-word:brillante) la detiene y hace sonar fuertemente sus enormes pinzas metálicas. Le advierte sobre el gran peligro y caos sónico que existe allá abajo... en lo más profundo e inexplorado del gigantesco mundo marino.",
    "Nia sonríe con extrema amabilidad, le agradece al gran cangrejo rojo y se asoma valientemente hacia el inmenso [abismo](magic-word:abismo) oscuro que los separa del fondo del océano, iluminando su camino con el hermoso destello mágico de su caracola."
  ],
  "nia_5": [
    "Nia empieza lentamente a [sumergirse](magic-word:sumergirse) cada vez más hondo, dejando atrás los corales luminosos para adentrarse en aguas misteriosamente oscuras. Con un gran suspiro de valentía admirable, comienza un descenso muy extenso donde la fuerte presión del océano frío se siente realmente inmensa y la escasa luz del sol ya no logra brillar.",
    "Pronto se encuentra justo frente al imponente borde de la gigantesca [trinchera](magic-word:trinchera) oceánica de rocas moradas. ¡Un lugar impresionante que muy pocas criaturas submarinas se atreven a explorar! Desde la enorme oscuridad profunda, sube una fuerte corriente circular acompañada de ruidos confusos y estresantes que perturban la tranquilidad de todo el mar.",
    "Escuchando pacientemente, la sabia niña del mar usa su antigua caracola luminosa para intentar descifrar los diferentes [ecos](magic-word:ecos) caóticos que rebotan velozmente contra las grandes paredes grises. Con enorme delicadeza, comienza a emitir un tono musical protector, creando una burbuja invisible de absoluto silencio acústico para calmar a todas las frágiles algas asustadas."
  ],
  "nia_6": [
    "Continuando su misteriosa aventura por el abismo submarino interminable, Nia descubre grandes [algas](magic-word:algas) verdes gigantescas. Estas enormes plantas marinas crecen majestuosamente desde el fondo rocoso y sus largas hojas ondulantes parecen intentar tocar la lejana superficie soleada... creando un enorme paisaje maravilloso que parece sacado de un mágico cuento de hadas.",
    "Al nadar con mucha calma entre las ramas verdes, la curiosa niña siente que ha entrado en un inmenso [bosque](magic-word:bosque) marino súper antiguo. El constante ruido tóxico hace vibrar fuertemente a las pobres plantas y enreda tristemente a los pequeños caballitos de mar asustados, impidiéndoles escapar del enorme laberinto vegetal.",
    "Nia decide detenerse pacientemente en medio del laberinto verde y simplemente [flotar](magic-word:flotar) con total tranquilidad sin mover un músculo. Entiende que luchar agresivamente contra la corriente marina sólo logrará empeorar la situación, así que utiliza el dulce canto de su caracola sanadora para desenredar suavemente cada hoja atrapada."
  ],
  "nia_7": [
    "Más abajo de las gigantescas plantas, el mar entero se vuelve increíblemente frío y casi aterradoramente negro. De repente... ¡una preciosa criatura [luminiscente](magic-word:luminiscente) pasa nadando muy elegantemente al lado de la niña asombrada! Dejando un espectacular rastro brillante de color azul eléctrico que parece polvillo cósmico volando por todo el vacío de las profundidades.",
    "A pesar de encontrarse completamente rodeada por la inmensa [oscuridad](magic-word:oscuridad), la valiente niña no siente ni una gota de miedo. Se da cuenta de que cuando el gigantesco mundo calla sus ruidos agresivos externos, se pueden apreciar fácilmente los hermosos destellos que intentan conversar musicalmente desde lo más oculto de los mares.",
    "El ruido caótico aparece fuertemente otra vez asustando a millones de diminutos bichitos marinos. El microscópico [plancton](magic-word:plancton) brilla desordenadamente a causa del gran pánico colectivo. Nia entonces comienza a soplar pacientemente la mágica caracola emitiendo una frecuencia muy lenta y pesada... ¡logrando sincronizar armónicamente el encendido y apagado de todas aquellas frágiles luces titilantes maravillosas!"
  ],
  "nia_8": [
    "Nia llega valientemente a una zona del océano que es absolutamente [silenciosa](magic-word:silenciosa) y calmada. La quietud total de las profundidades insondables es tan inmensamente poderosa, que parece ser un antiguo guardián invisible encargado de proteger un gran secreto oculto en la arena. La valiente niña respira tranquila y nada flotando en esa paz.",
    "Sin embargo, este profundo silencio sepulcral es un hermoso [espejismo](magic-word:espejismo). Repentinamente, un fuerte ruido rasposo similar a piedras gigantes chocando rasga el agua. Un gran tiburón dormilón se agita desesperadamente de un lado a otro sobre la fría arena del lecho marino... sin poder calmar sus nervios ni encontrar el descanso reparador que tanto necesita.",
    "Nia se acerca con gran compasión y ternura a la inmensa bestia gris. En vez de usar su caracola, la sabía niña usa sus propias manos desnudas para acariciar suavemente las ásperas escamas cerca del [branquial](magic-word:branquial) del gigante pez, tarareando una antigua melodía de cuna. El poderoso tiburón, sintiéndose seguro y profundamente amado, por fin cierra los ojos y vuelve a dormir."
  ],
  "nia_9": [
    "Dejando atrás al gran tiburón gris dormido plácidamente, Nia sigue la fría corriente hasta que encuentra un antiguo barco de madera hundido. Su deteriorado esqueleto roto y lleno de agujeros yace majestuosamente en el fondo, cubierto por completo de esponjas moradas y amarillas. Este mágico [naufragio](magic-word:naufragio) parece ser la inmensa caja de resonancia principal desde donde provienen todos los ruidos descontrolados.",
    "Al entrar con muchísimo cuidado por una de las viejas ventanas rotas y cubiertas de algas, la niña encuentra algo maravilloso y terrible al mismo tiempo. Un hermoso pulpo con tentáculos brillantes de un [tornasol](magic-word:tornasol) iridiscente golpea rápidamente las viejas maderas del barco con unas pesadas conchas marinas, creando una ensordecedora y caótica cacofonía metálica y molesta.",
    "El inteligente pulpo brillante, dándose cuenta de su presencia luminosa, se asusta y lanza una nube de tinta oscura ocultándose detrás de un pesado [timón](magic-word:timón) roto. Nia comprende rápidamente que el asustado molusco no quiere dañar el océano a propósito... ¡solamente se siente súper solo y está tocando esos ruidos horribles intentando desesperadamente llamar la atención de alguien que quiera ser su amigo!"
  ],
  "nia_10": [
    "Nia decide demostrarle al tímido pulpo asustado que no está solo en el oscuro abismo. Se queda completamente quieta frente al pesado timón, esperando con una sonrisa a que la oscura tinta se [disipe](magic-word:disipe) poco a poco en el agua cristalina. Sabe que la confianza sincera y verdadera no puede exigirse, sino que debe ganarse despacio mediante el respeto y la enorme amabilidad silenciosa.",
    "Cuando el agua vuelve a ser clara, la niña toma dos conchas marinas abandonadas en el antiguo piso del barco. En lugar de hacer ruidos molestos como los del pulpo, Nia empieza a golpear las conchas con un suave y hermoso ritmo constante, formando una pequeña [melodía](magic-word:melodía) invitadora. Su música es dulce y respetuosa, creando un juego musical sin invadir el frágil espacio del animal.",
    "El curioso pulpo asoma lentamente uno de sus largos tentáculos brillantes para devolver el suave toque, aceptando la amistosa invitación al juego rítmico. Cuando sus conchas chocan en perfecta y mágica [armonía](magic-word:armonía) con las de Nia, el terrible ruido caótico del barco se transforma inmediatamente en un bellísimo concierto sanador y pacífico."
  ],
  "nia_11": [
    "El nuevo amigo de ocho largos brazos parece inmensamente feliz. Para agradecer la amabilidad sincera de Nia, el brillante pulpo nada alegremente hacia el viejo y deteriorado camarote principal del capitán. Ahí adentro, escarba hábilmente la gruesa arena acumulada y le trae con cuidado un extraño [artefacto](magic-word:artefacto) oxidado de metal pesado y forma circular, lleno de misteriosas perlas blancas e incrustaciones doradas.",
    "Al observar el pesado objeto muy de cerca con su caracola luminosa, Nia se da cuenta de que es una antigua y muy compleja [brújula](magic-word:brújula) de navegación mágica. Sin embargo, su fina aguja dorada está atascada fuertemente, girando en círculos locos y vibrando rápidamente, produciendo un sutil y agudo pitido metálico constante que estresa el delicado fondo marino oscuro.",
    "La brillante y sabía niña deduce rápidamente que esta antigua y oxidada brújula atascada es el origen central de todas y cada una de las malas vibraciones sonoras de aquel abismo salado. El mágico objeto marino ha estado intentando desesperadamente durante muchísimos años mostrar el camino seguro y correcto hacia un gran secreto [ancestro](magic-word:ancestro), pero se estropeó por falta de música que la pudiera sanar."
  ],
  "nia_12": [
    "Nia sostiene cuidadosamente la vieja y descompuesta brújula con ambas manos pequeñas. Levanta valientemente su hermosa y resplandeciente caracola de nácar protector. Esta vez, la sabia niña no emite una sola nota musical simple, sino que respira muy profundo y canta una antigua [canción](magic-word:canción) de cuna oceánica sumamente compleja. Una canción heredada de las grandes ballenas sabias que viajan libres y sin miedo.",
    "Las hermosas ondas musicales sanadoras generadas por su voz dulce entran profundamente dentro del cerrado y oxidado [mecanismo](magic-word:mecanismo) del reloj metálico antiguo. Como si fuera verdadera e inmensa magia submarina antigua, la gruesa capa de sarro gris oscuro comienza a desprenderse sola y muy fácilmente. La aguja dorada brillante de la brújula se detiene de inmediato, y su molesto y agudo zumbido eléctrico molesto desaparece para siempre jamás.",
    "En vez de seguir girando descontroladamente hacia todos lados, la liberada y reparada aguja de oro puro ahora señala con una precisión absolutamente perfecta y clara hacia una lejana y oscura enorme grieta en las rocas del profundo lecho. El pulpo tornasol abraza suave y amistosamente la pierna derecha de Nia en agradecimiento puro antes de regresar a jugar tranquilo con su viejo timón arreglado y [seguro](magic-word:seguro)."
  ],
  "nia_13": [
    "Nia sigue valientemente la exacta dirección marcada por la resplandeciente aguja sanada de la vieja brújula. Se acerca lentamente nadando hacia la gigante y misteriosa hendidura ubicada entre dos altísimas montañas de roca morada oscura de la profundidad oceánica. En este remoto y callado rincón olvidado del mundo frío, la oscuridad inmensa es tan absolutamente completa que el pequeño [fulgor](magic-word:fulgor) protector de su amada caracola de nácar parece ser mágicamente y realmente la última luz viva de toda la tierra fría.",
    "De pronto... un profundo calor inesperado y sumamente agradable la recibe. La estrecha hendidura oscura se abre revelando una gigantesca caverna secreta que es alimentada por hermosas y burbujeantes fuentes de cálida agua [termal](magic-word:termal) mágica de color azulado. En el centro de esta iluminada cueva secreta descansa majestuosa y silenciosa una inmensa y preciosa perla blanca del gigantesco tamaño del sol resplandeciente de la mañana hermosa y brillante.",
    "Esta es verdaderamente el sagrado Corazón de las Mareas inmensas, el origen puro y ancestral del ritmo y los ciclos hermosos de todo el inmenso mar del mundo. Nia se detiene con gran respeto, cierra sus ojos oscuros e inclina su cabeza reverentemente, sabiendo que finalmente ha encontrado sana y salva lo que su gran aventura marina buscaba, gracias a su compasión verdadera por los seres tristes."
  ],
  "nia_14": [
    "Al tocar suave y delicadamente la inmensa superficie perfecta y suave de la perla blanca gigante con su manita tibia, el Corazón de las Mareas inmensas despierta y responde mágicamente. La gigantesca perla iluminada despide inmediatamente y sin demora un suave resplandor cálido verdaderamente hermoso y sumamente purificador, devolviendo a todo el inmenso océano misterioso entero su pacífico compás rítmico natural original. Los cientos y millones de peces naranjas en el [arrecife](magic-word:arrecife) lejano, los lindos caballitos de mar asustados e incluso el enorme tiburón dormilón descansan ahora en total armonía infinita.",
    "El gigantesco mundo marino completo vuelve de repente a cantar la más bellísima y maravillosa [sinfonía](magic-word:sinfonía) subacuática de paz profunda, demostrando al mundo exterior que ningún sonido molesto es demasiado fuerte o terrible si realmente y de verdad existe un noble y valiente corazón dispuesto a escuchar paciente y profundamente hasta curarlo amorosamente. Nia sonríe, y con un solo grácil aleteo de sus fuertes pies valientes, emprende felizmente su largo camino de regreso seguro hacia las aguas soleadas cristalinas.",
    "Al romper de nuevo la tibia y suave superficie espumosa del mar tranquilo tras su gran hazaña profunda, bañada por completo en la increíble luz naranja espectacular del alegre atardecer cálido perfecto del cielo, una repentina y muy fuerte brisa de calor seco, oliendo dulcemente a roca polvorienta dorada, cruza por su sonriente rostro feliz. Sabe que allá lejos, en un misterioso desierto muy distante e inexplorado por nadie jamás... el inmenso y seco Bioma de la Piedra ahora espera impacientemente escuchar muy pronto la maravillosa música [curativa](magic-word:curativa) de un nuevo amigo."
  ]
};
